---
title: "2018-12-12"
output: html_notebook
---

```{r}
library(readr)
library(dplyr)
library(stringr)
```


```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
libraryData$書籍館藏地 <- as.factor(libraryData$書籍館藏地)
levels(libraryData$書籍館藏地)->storageLocations
#libraryData$書籍館藏地 %>% as.factor %>% levels -> storageLocations
#storageLocations
```

```{r}
i<- 1
# 1
storageLocation_i <- storageLocations[i] 
# 2
numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
subsample_i <- libraryData[numericalIndexForSubsample,]
# 3
borrowCount_i <- nrow(subsample_i)
```

```{r}
# 0
allBorrowCount <- vector("numeric",18)
i<- 2
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i #[]一次可選很多位子 [[]]一次只能選一個位置
```

```{r}
allBorrowCount <- vector("numeric",18)
for (i in c (1:18)){
  i<- 2
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i
}
```

```{r}
# 0
allBorrowCount <- vector("numeric",18)
for(i in c(1:18)){
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i  
}
```

```{r}
as.factor(libraryData$學院) ->libraryData$學院
levels(libraryData$學院) ->college
```

```{r}
# 0
collegeBorrowCount <- vector("numeric",length(college)) #變數不需要_i
for(i in c(1:length(college))){
  # 1
  college_i <- college[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$學院 == college_i)
  collegesubsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  collegeborrowCount_i <- nrow(collegesubsample_i)
  # 4
  collegeBorrowCount[[i]]<-collegeborrowCount_i  
}
names(collegeBorrowCount) <- college
```

```{r}
as.factor(libraryData$學號) ->stuSubsample
# libraryData$學號 %>% unique ->stu
stuBorrow <- vector("numeric" , length(stu)) #for i in seq_along(stu)
for (i in c(1:length(stu))){
  stu_i <- stu[i]
  
  stuSubsample <-which(libraryData$學號 == stu_i)
  
  stuSub_i <-libraryData[stuSubsample,]
  
  stuBorrow_i <-nrow(stuSub_i)
  
  stuBorrow[[i]] <-stuBorrow_i
}
```

```{r}
libraryData %>%
  group_by(書籍館藏地) %>%
  summarise(
    borrowCount=length(學號)
  ) -> result
result
```

```{r}
libraryData %>%
  mutate(
    學系 = str_sub(學號 , 5 , 6)
  ) ->libraryData
```

```{r}
libraryData %>%
  group_by(學院,入學年) %>%
  summarise(
    borrowCount=length(學號)
  ) -> result2
result2
```

```{r}
enterYear <- as.factor(libraryData$入學年)
for (i in seq_along(college)){
  for (j in seq_along(enterYear)){
    
  }
}
```

```{r}
libraryData %>%
  filter(入學年 = 102 , ) #挑出特定條件計算
```

```{r}
as.factor(libraryData$學號) ->libraryData
ymd_hms(libraryData$借閱時間, tz = "Asia/Taipei") ->libraryData$借閱時間

group_by(libraryData$學號) %>%
  summarise(
    firstBorrrow = min(libraryData$借閱時間)
  ) ->result3
result3
```

