---
title: "2018-12-05"
output: html_notebook
---
 

```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
libraryData %>%
  mutate(
    學院 = as.factor(學院),
    書籍館藏地 = as.factor(書籍館藏地),
    書籍類別 = as.factor(書籍類別),
    借閱時間 = ymd_hms(借閱時間 , tz ="Asia/Taipei" )
  ) ->libraryData
```

```{r}
max(libraryData$讀者借閱冊數) ->max
min(libraryData$讀者借閱冊數) ->min
paste("最大值:" ,max , "最小值" , min)
#paste0("最大值:" ,max , "最小值" , min)

max(libraryData$入學年)
min(libraryData$入學年)

max(libraryData$書籍上架年月)
min(libraryData$書籍上架年月)
```
```{r}
minMaxFun <- function(x){
max(x) -> max
min(x) -> min
paste("最大值:" ,max , "最小值" , min) ->result
}
```

```{r}
minMaxFun3 <- function(x){
max(x) -> max
min(x) -> min
paste("最大值:" ,max , "最小值" , min) %>%
  print()
}
```

```{r}
minMaxFun2 <- function(x){
  max(x)-> maxNumber
  min(x)-> minNumber
  paste0("最大值： ",maxNumber, " 最小值： ",minNumber)-> output
  return(maxNumber) #只會顯示最大值
}
minMaxFun2(libraryData$讀者借閱冊數)-> outputValue2
outputValue2
```

```{r}
minMaxFun(libraryData$讀者借閱冊數) ->a1
minMaxFun(libraryData$書籍上架年月) ->a2
minMaxFun(libraryData$入學年) ->a3
```

```{r}
## 1
max(libraryData$讀者借閱冊數)-> maxNumber
min(libraryData$讀者借閱冊數)-> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber)

## 2
max(libraryData$入學年)-> maxNumber
min(libraryData$入學年)-> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber)

## 3
max(libraryData$書籍上架年月)-> maxNumber
min(libraryData$書籍上架年月)-> minNumber
paste0("最大值： ",maxNumber, " 最小值： ",minNumber)
```

```{r}
not_numeric<-function(x){
  !is.numeric(x) ->result
  return(result)
}
not_numeric(libraryData$書籍館藏地)
not_numeric(libraryData$讀者年級)
```

```{r}
library(dplyr)
#(libraryData$學院 == "人文學院") ->sub
#libraryData[sub,] ->sub
#(libraryData$學院 == "社會科學院") ->sub2
#libraryData[sub2,] ->sub2

college <-function(x){
  (libraryData$學院 == x) ->sub
  libraryData[sub , ]
}
college("社會科學院") ->sample1
college("人文學院") ->sample2
nrow(sample1)
nrow(sample2)
```

```{r}
library(dplyr)
libraryData %>%
  select(讀者借閱冊數,書籍出版日期) %>%
  summarise(
    讀者平均借閱冊數=mean(讀者借閱冊數),
    最小書籍出版日期=min(書籍出版日期 ,na.rm = T),
    最大書籍出版日期=max(書籍出版日期 , na.rm = T)
  )
```

```{r}
library(dplyr)
libraryData %>%
  group_by(學院) %>%
  summarise(
    學院借閱冊數 = length(學號)
  )
```

```{r}
library(summarytools)
library(summarytools)
libraryData %>%
  select_if(
    is.numeric
  ) %>% dfSummary() %>% 
view(.)
```

```{r}
(libraryData$書籍出版日期 == 1199) %>%
  which(.) %>%
  libraryData[. ,]
```

```{r}
library(summarytools)
libraryData %>%
  select_if(
   not_numeric
  ) %>% summarytools::dfSummary() %>% summarytools::view(.)
```


