---
title: "2018-11-7"
output: html_notebook
---


```{r}
library(stringr)
library(lubridate)
民國年月<-c("099/01","099/02","099/03")


```

```{r}
民國年月<-c("099/01","099/02","099/03")
library(dplyr)
library(stringr)
library(lubridate)
民國年月 %>% 
  str_c("1", . ,"/01") %>%
  ymd %>%
  { . + years(911) } #做運算時 , . 一定要打,並加{}
```

```{r}
library(readr)
collegeData <- read_csv("https://quality.data.gov.tw/dq_download_csv.php?nid=6231&md5_url=dda8fca407131483c1d8cbf3d61cf793")
```

```{r}
library(dplyr)
mutate(
  collegeData,
  學校代碼=as.factor(學校代碼),
  學校名稱=as.factor(學校名稱)
  ) -> collegeData2
```

```{r}
library(dplyr)
collegeData %>%
  mutate( 
  學校代碼 = as.factor(學校代碼) ,
  學校名稱 = as.factor(學校名稱)
  ) ->clasData2
```

```{r}
collegeData$學校代碼 <- as.factor(collegeData$學校代碼)
```

```{r}
library(stringr)
collegeData %>% 
  mutate(
     一年級男生 = str_replace(一年級男生,",",""),
     一年級女生 = str_replace(一年級女生,",","") ,
    `日間∕進修別`=as.factor(`日間∕進修別`),
    等級別=as.factor(等級別),
    一年級男生=as.numeric(一年級男生),
    一年級女生=as.numeric(一年級女生)
  ) -> collegeData3
```

```{r}
library(readr)
cl<-locale(grouping_mark = ",") # 創造cl來描述千分位符號使用","的習慣場景
collegeData %>% 
  mutate(
    `日間∕進修別`=as.factor(`日間∕進修別`),
    等級別=as.factor(等級別),
    一年級男生=parse_number(一年級男生,locale=cl),
    一年級女生=parse_number(一年級女生,locale=cl)
  ) -> collegeData4
```

```{r}
library(readr)
a <-locale(grouping_mark = ",")
collegeData %>%
  mutate(
    二年級男生 = parse_number(二年級男生,na =c("","NA","-"),locale = a)
  )
```

```{r}
problems(collegeData4$一年級男生)
```

```{r}
collegeData %>% mutate_at(
  vars(contains("生")),
  funs(parse_number(.,locale=a,na = c("","NA","-")))
) -> collegeNew

```


