---
title: "2018-10-31"
output: html_notebook
---



```{r}
library(stringr)
aa<-(str_sub(classSurvey$居住地行政區,1,3))
classSurvey[aa == "台北市",3]
```

```{r}
names(gsSurvey)
```

```{r}
gsSurvey$links$type
```

```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```

```{r}
as.numeric(student$身高)
x <-levels(student$身高 <= 170)
names(x)<-c("小個子") #錯了!!!!
```

```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```

```{r}
x <-as.character(classSurvey$學號)
library(stringr)
classSurvey$年級<-str_sub(x , 2 , 4)
classSurvey$年級 <-as.factor(classSurvey$年級)
levels(classSurvey$年級) <- c("大四及以上","大三","大二" ,"大一")
table(classSurvey$年級)
```

```{r}
student$新身高級距 <- student$身高級距
levels(student$身高級距)[c(1,3)] <-c("(0,160]")
```

```{r}
a <- classSurvey$本學期目前已參加之課外活動[(classSurvey$年級 =="大一")]
library(stringr)
str_split_fixed(a,",", n=5) ->b
str_c(b) -> c
table(c)
length(a) #大一人數
```

