---
title: "2018-12-19"
output: html_notebook
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr); library(stringr); library(lubridate); library(purrr)
```

```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
libraryData %>%
  filter(入學年==100, 學院=="社會科學院")
```

```{r}
libraryData %>%
  filter(between(入學年,100,102), 學院=="社會科學院")
# between()

libraryData %>%
  filter(入學年 %>% between(100,102), 學院=="社會科學院")
```

```{r}
a<-c(1:10)
typeof(a)

b<-list("a","b",1:10)
typeof(b) #list 元素格式不同
```

```{r}
b2<-list("a","b",1:10,
        list(         # 4th element in list
          "Mr Smith",
          data.frame(   # 2nd element in list
            v1=c(1,2),
            v2=c("aa","bb"),
            stringsAsFactors = F  # element in data.frame
          )
        ))
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
```

```{r}
filmVotingData$請選擇你最喜歡的影片二部 %>%
  str_split(", (?!(by))") -> filmVotingResult #(?!(by)) 可以去掉
#filmVotingResult                             
 #(?!(by)) 表示在 by 前面的 "," 不算在內，即不會切割 
```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1L,3L,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer[c("greenBox","redBox")] # or plasticContainer[c(1,2)]
#保有plasticContainer，等於只是把biueBox拿掉
```

```{r}
class(plasticContainer)
class(plasticContainer[c("greenBox")])
```

```{r}
plasticContainer[["greenBox"]] # or plasticContainer[[1]]
#相當於將 greenBox 從 plasticContainer 取出來
class(plasticContainer[["greenBox"]])
```


